print("🔥 Welcome To Burn Bot 🔥") 
name = input("What's your name?")
print("Interesting (not really)")
age = input("How old are you?")
print("Uhh, ok")
color = input("What's your favorite color?")
print("Lame")
food = input("What's you favorite food?")
print("Do you have anything... More creative?")
sport = input("What's your favorite sport or activity?")
print("That's what you enjoy doing!?")
print("Inputting Answers...   Writing Sick Burns...")
print(name, "Huh..., what a basic name.")
print(f"So you're {age} years old and yet you're favorite color is {color}. That's a color only a 6 year old would like.")
print(f"And {food}. Really. I couldn't have come up with a more basic answer if I tried. At least put some effort into it.")
print(f"Also, {sport}. Come on. I was doing that back when I was 2, and yet your're here, doing it at {age}.")
print(f"At this point, you should embrace the fact that you're nothing but a brainrotted little gen alpha kid and start yelling 67 every 3 seconds")